safe: true
markdown: kramdown
pygments: true
permalink: /:title.html
relative_permalinks: false

default_theme: bright
default_width: 792
default_lang: en
default_body_class: list

author:
    name: "Андрей [8xx8] Кулаков"
    # url:  http://example.com/
    company:
        name: Waytag.ru
        # url:  http://example.com/

progress: true
line_numbers: true
username: Andrew8xx8
